---
"$schema": http://json-schema.org/draft-04/hyper-schema
description: infra-metrics API v1 Alpha Document
id: infra-metrics
links:
- href: https://<your-infra-metrics-server>.com
  rel: self
  title: infra-metrics API v1 Alpha
